name: Generate ASCII Art Work
on: push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: checkout Repo files
          run:  ls -lrsta

        - name: Executing the Shell Script
          run: |
                sh ascii-script.sh
        - name: checkout Repo files
          run:  ls -lrsta